M48
; DRILL file {KiCad (7.0.0)} date Sun Feb 26 23:15:06 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-26T23:15:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X226.595Y-38.905
X226.595Y-60.905
X248.595Y-38.905
X248.595Y-60.905
T2
X212.5Y-25.0
X262.5Y-75.0
T0
M30
